{"name": "test_create_auth_with_excel", "status": "broken", "statusDetails": {"message": "openpyxl.utils.exceptions.InvalidFileException: openpyxl does not support .py file format, please check you can open it with Excel first. Supported formats are: .xlsx,.xlsm,.xltx,.xltm", "trace": "def test_create_auth_with_excel():\n        file_path=\"C:/Users/somes/PycharmProjects/PythonAPIAutomation2X/tests/test/Data-Driven-Testing/test_ddt_for_loop.py\"\n>       credentials=read_credentials(file_path=file_path)\n\ntest_ddt_for_loop.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest_ddt_for_loop.py:9: in read_credentials\n    workbook=openpyxl.load_workbook(filename=file_path)\n..\\..\\..\\.venv\\Lib\\site-packages\\openpyxl\\reader\\excel.py:346: in load_workbook\n    reader = ExcelReader(filename, read_only, keep_vba,\n..\\..\\..\\.venv\\Lib\\site-packages\\openpyxl\\reader\\excel.py:123: in __init__\n    self.archive = _validate_archive(fn)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nfilename = 'C:/Users/somes/PycharmProjects/PythonAPIAutomation2X/tests/test/Data-Driven-Testing/test_ddt_for_loop.py'\n\n    def _validate_archive(filename):\n        \"\"\"\n        Does a first check whether filename is a string or a file-like\n        object. If it is a string representing a filename, a check is done\n        for supported formats by checking the given file-extension. If the\n        file-extension is not in SUPPORTED_FORMATS an InvalidFileException\n        will raised. Otherwise the filename (resp. file-like object) will\n        forwarded to zipfile.ZipFile returning a ZipFile-Instance.\n        \"\"\"\n        is_file_like = hasattr(filename, 'read')\n        if not is_file_like:\n            file_format = os.path.splitext(filename)[-1].lower()\n            if file_format not in SUPPORTED_FORMATS:\n                if file_format == '.xls':\n                    msg = ('openpyxl does not support the old .xls file format, '\n                           'please use xlrd to read this file, or convert it to '\n                           'the more recent .xlsx file format.')\n                elif file_format == '.xlsb':\n                    msg = ('openpyxl does not support binary format .xlsb, '\n                           'please convert this file to .xlsx format if you want '\n                           'to open it with openpyxl')\n                else:\n                    msg = ('openpyxl does not support %s file format, '\n                           'please check you can open '\n                           'it with Excel first. '\n                           'Supported formats are: %s') % (file_format,\n                                                           ','.join(SUPPORTED_FORMATS))\n>               raise InvalidFileException(msg)\nE               openpyxl.utils.exceptions.InvalidFileException: openpyxl does not support .py file format, please check you can open it with Excel first. Supported formats are: .xlsx,.xlsm,.xltx,.xltm\n\n..\\..\\..\\.venv\\Lib\\site-packages\\openpyxl\\reader\\excel.py:93: InvalidFileException"}, "start": 1739642560557, "stop": 1739642560559, "uuid": "89bf4289-28d7-4d96-b8e1-6f00c8079550", "historyId": "a0d23a049cc9d5ff6ee2ace1d0340627", "testCaseId": "a0d23a049cc9d5ff6ee2ace1d0340627", "fullName": "tests.test.Data-Driven-Testing.test_ddt_for_loop#test_create_auth_with_excel", "labels": [{"name": "parentSuite", "value": "tests.test.Data-Driven-Testing"}, {"name": "suite", "value": "test_ddt_for_loop"}, {"name": "host", "value": "someshcom065"}, {"name": "thread", "value": "7744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.Data-Driven-Testing.test_ddt_for_loop"}]}